// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJqbJfeoQvlWCoomJX5_aX0rkspBUfI8',
    appId: '1:166289878640:android:283b8d018d06fda2354eb5',
    messagingSenderId: '166289878640',
    projectId: 'medihelp-d4bc5',
    storageBucket: 'medihelp-d4bc5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNdWDISZgQvXj8QptwQH2eacvv8aD_GXo',
    appId: '1:166289878640:ios:d9ef1851f3884e8d354eb5',
    messagingSenderId: '166289878640',
    projectId: 'medihelp-d4bc5',
    storageBucket: 'medihelp-d4bc5.firebasestorage.app',
    androidClientId: '166289878640-6t76nn7nqtl9n5qtpejisn16dsoe24ra.apps.googleusercontent.com',
    iosClientId: '166289878640-bobre9trjaeoompb6ji8mpkeecg1b0a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

}